In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/outputs/weekly_forecasts.csv")

In [6]:
df.model_version.value_counts()

model_version
weekly_model_v3_calendar      1680
weekly_model_v4_promotions     840
Name: count, dtype: int64

In [7]:
df.head()

,week_start,store_id,product_id,predicted_units,forecast_created_at,model_version
0,2026-03-30,1,1001,7.31,2026-04-06,weekly_model_v4_promotions
1,2026-03-30,1,1002,12.27,2026-04-06,weekly_model_v4_promotions
2,2026-03-30,1,1003,24.83,2026-04-06,weekly_model_v4_promotions
3,2026-03-30,1,1004,6.84,2026-04-06,weekly_model_v4_promotions
4,2026-03-30,1,1005,29.16,2026-04-06,weekly_model_v4_promotions

In [ ]:
display(df[["store_name","product_name","category","predicted_units","regular_price"]].head(15))

In [8]:
display(df[["week_start", "store_id", "product_id", "predicted_units", "forecast_created_at"]].head())

   week_start  store_id  product_id  predicted_units forecast_created_at
0  2026-03-30         1        1001             7.31          2026-04-06
1  2026-03-30         1        1002            12.27          2026-04-06
2  2026-03-30         1        1003            24.83          2026-04-06
3  2026-03-30         1        1004             6.84          2026-04-06
4  2026-03-30         1        1005            29.16          2026-04-06

In [9]:
df[["week_start", "store_id", "product_id", "predicted_units", "forecast_created_at"]].head()

   week_start  store_id  product_id  predicted_units forecast_created_at
0  2026-03-30         1        1001             7.31          2026-04-06
1  2026-03-30         1        1002            12.27          2026-04-06
2  2026-03-30         1        1003            24.83          2026-04-06
3  2026-03-30         1        1004             6.84          2026-04-06
4  2026-03-30         1        1005            29.16          2026-04-06

In [11]:
from IPython.display import display

print("Forecast sample:")
df.head()

Forecast sample:

,week_start,store_id,product_id,predicted_units,forecast_created_at,model_version
0,2026-03-30,1,1001,7.31,2026-04-06,weekly_model_v4_promotions
1,2026-03-30,1,1002,12.27,2026-04-06,weekly_model_v4_promotions
2,2026-03-30,1,1003,24.83,2026-04-06,weekly_model_v4_promotions
3,2026-03-30,1,1004,6.84,2026-04-06,weekly_model_v4_promotions
4,2026-03-30,1,1005,29.16,2026-04-06,weekly_model_v4_promotions

In [12]:
from IPython.display import display

print("Forecast sample:")
display(df.head())

Forecast sample:

,week_start,store_id,product_id,predicted_units,forecast_created_at,model_version
0,2026-03-30,1,1001,7.31,2026-04-06,weekly_model_v4_promotions
1,2026-03-30,1,1002,12.27,2026-04-06,weekly_model_v4_promotions
2,2026-03-30,1,1003,24.83,2026-04-06,weekly_model_v4_promotions
3,2026-03-30,1,1004,6.84,2026-04-06,weekly_model_v4_promotions
4,2026-03-30,1,1005,29.16,2026-04-06,weekly_model_v4_promotions